export const levelData = [
  {
    backgroundColor: "#cee673",
    hoverColor: "#5957e0",
    speed: "4.2s",
    icons: ["🙂", "🙃"],
  },
  {
    backgroundColor: "#8add99",
    hoverColor: "#db0090",
    speed: "3.7s",
    icons: ["🐣", "🐤", "🐥", "🐦"],
  },
  {
    backgroundColor: "#318c6b",
    hoverColor: "#e4e843",
    speed: "3.2s",
    icons: ["🩲", "🧤", "🧦", "👕", "👖"],
  },
  {
    backgroundColor: "#66d3d0",
    hoverColor: "#95d879",
    speed: "2.7s",
    icons: ["🙍", "🙎", "🙅", "🙆", "🤷", "🤦", "🙇"],
  },
  {
    backgroundColor: "#50a4ff",
    hoverColor: "#e068e0",
    speed: "2.2s",
    icons: ["😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾"],
  },
  {
    backgroundColor: "#3b4eff",
    hoverColor: "#db5883",
    speed: "1.7s",
    icons: ["🦟", "🪰", "🪳", "🦗", "🐞", "🪲", "🐝", "🐜", "🐛", "🦋", "🐌"],
  },
  {
    backgroundColor: "#ffb76d",
    hoverColor: "#fe6fb9",
    speed: "1.2s",
    icons: [
      "🐱",
      "🐵",
      "🐶",
      "🐺",
      "🦊",
      "🦝",
      "🦁",
      "🐯",
      "🐷",
      "🐻",
      "🐨",
      "🐼",
      "🐭",
      "🐸",
    ],
  },
  {
    backgroundColor: "#ff7761",
    hoverColor: "#7aea97",
    speed: "0.7s",
    icons: [
      "🥝",
      "🍍",
      "🍌",
      "🍋",
      "🍊",
      "🍉",
      "🍈",
      "🫐",
      "🍓",
      "🍒",
      "🍑",
      "🍐",
      "🍏",
      "🍎",
      "🍇",
    ],
  },
  {
    backgroundColor: "#e53e3e",
    hoverColor: "#965fed",
    speed: "0.2s",
    icons: [
      "🦛",
      "🦏",
      "🦣",
      "🐘",
      "🦒",
      "🦙",
      "🐫",
      "🐪",
      "🐐",
      "🐑",
      "🐏",
      "🐖",
      "🐄",
      "🐃",
      "🐂",
      "🦬",
      "🦌",
      "🐎",
      "🐆",
      "🐅",
      "🐈",
      "🐩",
      "🐕",
      "🦮",
    ],
  },
];
